name: sentinel-test-azure
on:
  pull_request:
    branches:
      - master
    paths:
      - 'azure/**'

jobs:
  sentinel-test-azure:
    runs-on: ubuntu-latest
    steps:
      # This step checks out the repository's code
      - uses: actions/checkout@v1
      # This step runs `sentinel test` against the Azure policies
      - name: sentinel-test-azure
        uses: rberlind/sentinel-policy-sets-for-tfc/.github/actions/run-sentinel@master
        with:
          args: ./azure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
