name: sentinel-test-azure
on:
  pull_request:
    branches:
      - master
    paths:
      - 'sentinel-policy-sets/azure/**'

jobs:
  sentinel-test-azure:
    runs-on: ubuntu-latest
    steps:
      # This step checks out the repository's code
      - uses: actions/checkout@v1
      # This step runs `sentinel test` against the Azure policies
      - name: sentinel-test-azure
        uses: ./.github/actions/run-sentinel
        with:
          args: ./sentinel-policy-sets/azure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
