name: sentinel-test-gcp
on:
  pull_request:
    branches:
      - master
    paths:
      - 'sentinel-policy-sets/gcp/**'

jobs:
  sentinel-test-gcp:
    runs-on: ubuntu-latest
    steps:
      # This step checks out the repository's code
      - name: checkout-code
        uses: actions/checkout@v1
        with:
          path: /github/workspace
      # This step runs `sentinel test` against the GCP policies
      - name: sentinel-test-gcp
        uses: rberlind/sentinel-policy-sets-for-tfc@master
        with:
          args: /github/workspace/sentinel-policy-sets/gcp
        env:
          STL_ACTION_WORKING_DIR: '/github/workspace/sentinel-policy-sets/gcp'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
