name: sentinel-test-gcp
on:
  pull_request:
    branches:
      - master
    paths:
      - 'sentinel-policy-sets/gcp/**'

jobs:
  sentinel-test-gcp:
    runs-on: ubuntu-latest
    steps:
      # This step runs `sentinel test` against the GCP policies
      - name: sentinel-test-gcp
        uses: rberlind/sentinel-policy-sets-for-tfc@master
        with:
          args: ./sentinel-policy-sets/gcp
        env:
          STL_ACTION_WORKING_DIR: './sentinel-policy-sets/gcp'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
