name: sentinel-test-gcp
on:
  pull_request:
    branches:
      - master
    paths:
      - 'gcp/**'

jobs:
  sentinel-test-gcp:
    runs-on: ubuntu-latest
    steps:
      # This step checks out the repository's code
      - uses: actions/checkout@v1
      # This step runs `sentinel test` against the GCP policies
      - name: sentinel-test-gcp
        uses: rberlind/sentinel-policy-sets-for-tfc/.github/actions/run-sentinel@master
        with:
          args: ./gcp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
