on: pull_request
name: sentinel
jobs:
  sentinel-test-vmware:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: sentinel-test-vmware
      uses: rberlind/sentinel-github-actions/test@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        STL_ACTION_WORKING_DIR: ./sentinel-policy-sets/vmware
    - name: sentinel-test-gcp
      uses: rberlind/sentinel-github-actions/test@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        STL_ACTION_WORKING_DIR: ./sentinel-policy-sets/gcp
    - name: sentinel-test-azure
      uses: rberlind/sentinel-github-actions/test@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        STL_ACTION_WORKING_DIR: ./sentinel-policy-sets/azure
    - name: sentinel-test-aws
      uses: rberlind/sentinel-github-actions/test@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        STL_ACTION_WORKING_DIR: ./sentinel-policy-sets/aws
